### ISSUE TITLE
Extension fails to start after latest update

### ISSUE THREAD

**Issue by thatguy7669** [tghosgor/gnome-shell-extension-alsamixer#5]
After updating to latest version, the extension fails to start and gives the following error:
TypeError: extension is null
Error: expected type object for Argument 'actor' but got type 'undefined'

Disabling/re-enabling and uninstalling/reinstalling the extension did not work.

Happy for any assistance.

**Comment by tghosgor** [comment]
What is the version of the gnome-shell?

**Comment by thatguy7669** [comment]
Gnome-shell version 3.28 and extension version 31. When I try downgrading the extension version,  the extension fails to even get recognized.
Looking glass does not provide line numbers

**Comment by tghosgor** [comment]
Does `journalctl /usr/bin/gnome-shell` show the line numbers then?

**Comment by thatguy7669** [comment]
Unfortunately no

**Comment by tghosgor** [comment]
Okay, thanks.

Could you please change `this.icon.actor` to `this.icon` on line 46 of file `~/.local/share/gnome-shell/extensions/Alsa_Mixer@fasdfasdas.gmail.com/extension.js` and reload the extension somehow (`Alt-F2 && r<enter>` for Xorg, logout/login on Wayland).

**Comment by thatguy7669** [comment]
That  causes the following error: TypeError: setting a property that has only a getter
in lines 155 & 169

**Comment by tghosgor** [comment]
Apparently that line should be `this._menu.slider.setValue(percent / 100);` for 3.28.

**Comment by tghosgor** [comment]
I will publish a new release if there isn't any compatibility issues any more.

**Comment by tghosgor** [comment]
You should probably also change line 72 from `'notify::value'` to `'value-changed'`.

**Comment by thatguy7669** [comment]
That  causes the following error: TypeError: setting a property that has only a getter
in lines 155 & 169.
The change to line 73 did the trick. Everything working as expected.
Thank you for the fast and effective support.

**Comment by tghosgor** [comment]
You're welcome.

Let's hope the way I tried to handle the compatibility in [latest state of the file](https://github.com/tghosgor/gnome-shell-extension-alsamixer/blob/c3b81983626da2a59644ad7e6623a86ddcbda1db/extension.js) works fine in 3.28.
