### ISSUE TITLE
extension does not start on login, cannot control volume, does not replace original sound indicator

### ISSUE THREAD

**Issue by chaosmonk1** [tghosgor/gnome-shell-extension-alsamixer#6]
Hi, I am running GNOME 3.30 on Debian 10.  I have encountered three issues so far.

* Upon enabling the extension, I have two sound indicators in the status bar: the original pulseaudio sound indicator, and the extension's indicator.

* I tried logging out and logging in again to see if the pulseaudio sound indicator would go away.  Instead, the extension's sound indicator is gone.  The only way to get it back after login is to disable and re-enable the addon.

* The extension's sound indicator and the volume slider in the dropdown menu accurately *reflect* ALSA's volume, but they cannot not modify it.  I can drag the volume slider, and mouse wheel over the indicator affects the volume slider, but the slider quickly jumps back to its original position, and volume is unaffected.

`alsa-utils` is installed.  Perhaps this extension does not work when pulseaudio is running.  Is that the case?

**Comment by chaosmonk1** [comment]
I renamed `/usr/bin/pulseaudio` to `/usr/bin/pulseaudio.bak` to prevent it from starting.  This fixed the first two issues.  The extension's sound indicator starts on login, and the original sound indicator doesn't.  However, the third issue persists.  The indicator and volume slider respond to volume changes made in alsamixer, but they cannot be used to make volume changes.  Also, sound does not work now.  Running `speaker-test` (which should not require pulseaudio) gives me
```
ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
Playback open error: -16,Device or resource busy
```

**Comment by tghosgor** [comment]
The extension does not modify your system to disable pulse and enable alsa. It's merely a controller for alsa volume.

You could refer to your distro wiki on how to disable pulse and use alsa.

**Comment by chaosmonk1** [comment]
> The extension does not modify your system to disable pulse and enable
> alsa. It's merely a controller for alsa volume.

I understand that.  The problem is that the extension is not controlling
ALSA's volume.

"disable pulse and enable alsa" does not really make sense to me.
Pulseaudio depends on ALSA, so if pulseaudio is in use then ALSA is
already enabled.  Other ALSA frontends, such as alsamixer, can control
ALSA's volume whether or not pulseaudio is running.  Are you saying that
this extension cannot do this?

**Comment by tghosgor** [comment]
> Are you saying that
this extension cannot do this?

Maybe. Probably. I haven't used it with pulseaudio installed/enabled therefore its not tested.

Anyway this is out of scope for this extension to work alongside pulseaudio for me. PA already has the controls that you will get by adjusting alsa afaik. Feel free to provide a patch that does this if you think it's worth the time.

**Comment by chaosmonk1** [comment]
> Anyway this is out of scope for this extension to work alongside
> pulseaudio for me.

Ok, thanks for clarifying.

> PA already has the controls that you will get by adjusting alsa afaik.

My use case is an audio production environment where some applications
are managed by JACK and others by pulseaudio, so ALSA's master volume is
the only way to affect the volume of all applications globally.
alsamixer and mappings to amixer commands work fine, but I'm looking for
a solution which better integrates with GNOME.  This is not a common
situation, so I don't expect you to implement support for it.  I was
just checking to see if it was already possible.

> Feel free to provide a patch that does this if you think it's worth
> the time.

Thanks, it's good to know that you would welcome a patch.  If I cannot
first find an existing solution elsewhere I will make an attempt.

**Comment by tghosgor** [comment]
I may look into it if I have the time. As you said, there should not be a reason for it to not work after all. The indicator is explicitly disabled if PA is there as far as I remember, I might have disabled it's functionality also but I can't remember atm.
